<?php

define('OU_BAGIT_IMPORTER_OBJECT_NAMESPACE', 'islandora');

/**
 * Creates/Updates a book collection.
 */
function ou_bagit_importer_save_book_collection($object_array, $json_recipe) {
  global $user;
  $parent_collection = 'islandora:bookCollection';
  $tuque = islandora_get_tuque_connection();
  $uuid = OU_BAGIT_IMPORTER_OBJECT_NAMESPACE . ":{$object_array['uuid']}";
  $islandora_object = islandora_object_load($uuid);
  $update = (bool) $json_data['update'];
  $content_models = array(
    $object_array['type'],
    'fedora-system:FedoraObject-3.0',
  );
  if ($islandora_object && !$update) {
    drupal_set_message('Book collection object exists');
    return;
  }
  // Set up islandora object
  if (!$islandora_object) {
    $islandora_object = $tuque->repository->constructObject(OU_BAGIT_IMPORTER_OBJECT_NAMESPACE . ":{$object_array['uuid']}");
    $islandora_object->id = OU_BAGIT_IMPORTER_OBJECT_NAMESPACE . ":{$object_array['uuid']}";
    $islandora_object->state = 'A';
    $islandora_object->label = $object_array['uuid'];
    $islandora_object->owner = $user->name;
    foreach ($content_models as $content_model) {
      $islandora_object->relationships->add(FEDORA_MODEL_URI, 'hasModel', $content_model);
    }
    $islandora_object->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $parent_collection);
  }
  $mods_record = ou_bagit_importer_run_xslt_transform(array(
    'input' => file_get_contents($object_array['metadata']['marcxml']),
    'xsl' => drupal_get_path('module', 'islandora_marcxml') . '/xsl/MARC21slim2MODS3-5.xsl',
  ));
  $dc_record = ou_bagit_importer_run_xslt_transform(array(
    'input' => $mods_record,
    'xsl' => drupal_get_path('module', 'islandora_batch') . '/transforms/mods_to_dc.xsl',
  ));
  $finfo = finfo_open(FILEINFO_MIME_TYPE);
  $datastreams = array(
    'MODS' => array(
      'type' => 'text/xml',
      'content' => $mods_record,
    ),
    'DC' => array(
      'type' => 'text/xml',
      'content' => $dc_record,
    ),
    'TN' => array(
      'type' => finfo_file($finfo, drupal_realpath($object_array['metadata']['thumbnail'])),
      'content' => file_get_contents($object_array['metadata']['thumbnail']),
    ),
  );
  finfo_close($finfo);
  foreach ($datastreams as $key => $value) {
    if (!$islandora_object[$key]) {
      $ds = $islandora_object->constructDatastream($key);
      $ds->label = $key;
      $ds->mimetype = $value['type'];
      $ds->control_group = 'I';
      $ds->setContentFromString($value['content']);
      $islandora_object->ingestDatastream($ds);
    }
  }
  islandora_add_object($islandora_object);
}

function ou_bagit_importer_run_xslt_transform($info) {
  $xsl = new DOMDocument();
  $xsl->load($info['xsl']);

  $input = new DOMDocument();
  $input->loadXML($info['input']);

  $processor = new XSLTProcessor();
  $processor->importStylesheet($xsl);

  if (isset($info['php_functions'])) {
    $processor->registerPHPFunctions($info['php_functions']);
  }

  // XXX: Suppressing warnings regarding unregistered prefixes.
  return $processor->transformToXML($input);
}
